2022-11-22 19:16:19,606 INFO    StreamThr :37629 [internal.py:wandb_internal():88] W&B internal server running at pid: 37629, started at: 2022-11-22 19:16:19.605908
2022-11-22 19:16:19,609 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: status
2022-11-22 19:16:19,611 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: status
2022-11-22 19:16:19,613 INFO    WriterThread:37629 [datastore.py:open_for_write():75] open: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/run-3gudo1hi.wandb
2022-11-22 19:16:19,613 DEBUG   SenderThread:37629 [sender.py:send():303] send: header
2022-11-22 19:16:19,613 DEBUG   SenderThread:37629 [sender.py:send():303] send: run
2022-11-22 19:16:19,633 INFO    SenderThread:37629 [sender.py:_maybe_setup_resume():593] checking resume status for None/YOLOR/3gudo1hi
2022-11-22 19:16:24,611 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:29,615 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:34,618 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:39,621 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:44,623 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:46,273 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: check_version
2022-11-22 19:16:46,275 INFO    SenderThread:37629 [dir_watcher.py:__init__():216] watching files in: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files
2022-11-22 19:16:46,275 INFO    SenderThread:37629 [sender.py:_start_run_threads():928] run started: 3gudo1hi with start time 1669115779.602527
2022-11-22 19:16:46,275 DEBUG   SenderThread:37629 [sender.py:send():303] send: summary
2022-11-22 19:16:46,276 INFO    SenderThread:37629 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:16:46,276 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: check_version
2022-11-22 19:16:47,285 INFO    Thread-17 :37629 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/wandb-summary.json
2022-11-22 19:16:47,631 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: run_start
2022-11-22 19:16:47,634 DEBUG   HandlerThread:37629 [system_info.py:__init__():31] System info init
2022-11-22 19:16:47,634 DEBUG   HandlerThread:37629 [system_info.py:__init__():46] System info init done
2022-11-22 19:16:47,634 INFO    HandlerThread:37629 [system_monitor.py:start():150] Starting system monitor
2022-11-22 19:16:47,634 INFO    SystemMonitor:37629 [system_monitor.py:_start():116] Starting system asset monitoring threads
2022-11-22 19:16:47,635 INFO    SystemMonitor:37629 [interfaces.py:start():168] Started cpu
2022-11-22 19:16:47,635 INFO    SystemMonitor:37629 [interfaces.py:start():168] Started disk
2022-11-22 19:16:47,635 INFO    HandlerThread:37629 [system_monitor.py:probe():168] Collecting system info
2022-11-22 19:16:47,636 INFO    SystemMonitor:37629 [interfaces.py:start():168] Started gpu
2022-11-22 19:16:47,636 INFO    SystemMonitor:37629 [interfaces.py:start():168] Started memory
2022-11-22 19:16:47,637 INFO    SystemMonitor:37629 [interfaces.py:start():168] Started network
2022-11-22 19:16:47,668 DEBUG   HandlerThread:37629 [system_info.py:probe():195] Probing system
2022-11-22 19:16:47,673 DEBUG   HandlerThread:37629 [git.py:repo():40] git repository is invalid
2022-11-22 19:16:47,673 DEBUG   HandlerThread:37629 [system_info.py:probe():241] Probing system done
2022-11-22 19:16:47,673 DEBUG   HandlerThread:37629 [system_monitor.py:probe():177] {'os': 'Linux-5.15.0-53-generic-x86_64-with-glibc2.17', 'python': '3.8.13', 'heartbeatAt': '2022-11-22T11:16:47.668463', 'startedAt': '2022-11-22T11:16:19.595210', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/rp/DeepLearning/yolov7-main/train.py', 'codePath': 'train.py', 'host': 'rp', 'username': 'rp', 'executable': '/home/rp/Softwares/anaconda3/envs/dyh/bin/python', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2969.3500625, 'min': 800.0, 'max': 4800.0}, 'cpu_freq_per_core': [{'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 4009.601, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}], 'disk': {'total': 937.3305015563965, 'used': 300.82155990600586}, 'gpu': 'NVIDIA GeForce RTX 3080', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10497294336}], 'memory': {'total': 31.272598266601562}}
2022-11-22 19:16:47,673 INFO    HandlerThread:37629 [system_monitor.py:probe():178] Finished collecting system info
2022-11-22 19:16:47,673 INFO    HandlerThread:37629 [system_monitor.py:probe():181] Publishing system info
2022-11-22 19:16:47,673 DEBUG   HandlerThread:37629 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2022-11-22 19:16:47,675 DEBUG   HandlerThread:37629 [system_info.py:_save_pip():67] Saving pip packages done
2022-11-22 19:16:47,675 DEBUG   HandlerThread:37629 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2022-11-22 19:16:48,285 INFO    Thread-17 :37629 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/requirements.txt
2022-11-22 19:16:48,286 INFO    Thread-17 :37629 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/conda-environment.yaml
2022-11-22 19:16:50,138 DEBUG   HandlerThread:37629 [system_info.py:_save_conda():86] Saving conda packages done
2022-11-22 19:16:50,145 INFO    HandlerThread:37629 [system_monitor.py:probe():183] Finished publishing system info
2022-11-22 19:16:50,183 DEBUG   SenderThread:37629 [sender.py:send():303] send: files
2022-11-22 19:16:50,183 INFO    SenderThread:37629 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-11-22 19:16:50,194 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: stop_status
2022-11-22 19:16:50,194 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: stop_status
2022-11-22 19:16:50,286 INFO    Thread-17 :37629 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/conda-environment.yaml
2022-11-22 19:16:50,286 INFO    Thread-17 :37629 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/wandb-metadata.json
2022-11-22 19:16:52,531 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: poll_exit
2022-11-22 19:16:55,563 DEBUG   SenderThread:37629 [sender.py:send():303] send: telemetry
2022-11-22 19:16:55,563 DEBUG   SenderThread:37629 [sender.py:send():303] send: telemetry
2022-11-22 19:16:55,564 DEBUG   SenderThread:37629 [sender.py:send():303] send: config
2022-11-22 19:16:55,565 DEBUG   SenderThread:37629 [sender.py:send():303] send: config
2022-11-22 19:16:55,591 DEBUG   SenderThread:37629 [sender.py:send():303] send: exit
2022-11-22 19:16:55,591 INFO    SenderThread:37629 [sender.py:send_exit():442] handling exit code: 0
2022-11-22 19:16:55,592 INFO    SenderThread:37629 [sender.py:send_exit():444] handling runtime: 3
2022-11-22 19:16:55,593 INFO    SenderThread:37629 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:16:55,594 INFO    SenderThread:37629 [sender.py:send_exit():450] send defer
2022-11-22 19:16:55,594 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: poll_exit
2022-11-22 19:16:55,596 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:55,596 INFO    HandlerThread:37629 [handler.py:handle_request_defer():162] handle defer: 0
2022-11-22 19:16:55,597 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:55,598 INFO    SenderThread:37629 [sender.py:send_request_defer():459] handle sender defer: 0
2022-11-22 19:16:55,598 INFO    SenderThread:37629 [sender.py:transition_state():463] send defer: 1
2022-11-22 19:16:55,599 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:55,599 INFO    HandlerThread:37629 [handler.py:handle_request_defer():162] handle defer: 1
2022-11-22 19:16:55,599 INFO    HandlerThread:37629 [system_monitor.py:finish():160] Stopping system monitor
2022-11-22 19:16:55,600 DEBUG   SystemMonitor:37629 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2022-11-22 19:16:55,601 DEBUG   SystemMonitor:37629 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2022-11-22 19:16:55,602 DEBUG   SystemMonitor:37629 [system_monitor.py:_start():141] Publishing last batch of metrics
2022-11-22 19:16:55,605 INFO    HandlerThread:37629 [interfaces.py:finish():173] Joined cpu
2022-11-22 19:16:55,606 INFO    HandlerThread:37629 [interfaces.py:finish():173] Joined disk
2022-11-22 19:16:55,656 INFO    HandlerThread:37629 [interfaces.py:finish():173] Joined gpu
2022-11-22 19:16:55,656 INFO    HandlerThread:37629 [interfaces.py:finish():173] Joined memory
2022-11-22 19:16:55,656 INFO    HandlerThread:37629 [interfaces.py:finish():173] Joined network
2022-11-22 19:16:55,656 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:55,656 INFO    SenderThread:37629 [sender.py:send_request_defer():459] handle sender defer: 1
2022-11-22 19:16:55,656 INFO    SenderThread:37629 [sender.py:transition_state():463] send defer: 2
2022-11-22 19:16:55,657 DEBUG   SenderThread:37629 [sender.py:send():303] send: stats
2022-11-22 19:16:55,657 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:55,657 INFO    HandlerThread:37629 [handler.py:handle_request_defer():162] handle defer: 2
2022-11-22 19:16:55,657 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:55,657 INFO    SenderThread:37629 [sender.py:send_request_defer():459] handle sender defer: 2
2022-11-22 19:16:55,658 INFO    SenderThread:37629 [sender.py:transition_state():463] send defer: 3
2022-11-22 19:16:55,658 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:55,658 INFO    HandlerThread:37629 [handler.py:handle_request_defer():162] handle defer: 3
2022-11-22 19:16:55,658 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:55,658 INFO    SenderThread:37629 [sender.py:send_request_defer():459] handle sender defer: 3
2022-11-22 19:16:55,658 INFO    SenderThread:37629 [sender.py:transition_state():463] send defer: 4
2022-11-22 19:16:55,658 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:55,658 INFO    HandlerThread:37629 [handler.py:handle_request_defer():162] handle defer: 4
2022-11-22 19:16:55,659 DEBUG   SenderThread:37629 [sender.py:send():303] send: summary
2022-11-22 19:16:55,659 INFO    SenderThread:37629 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:16:55,659 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:55,659 INFO    SenderThread:37629 [sender.py:send_request_defer():459] handle sender defer: 4
2022-11-22 19:16:55,659 INFO    SenderThread:37629 [sender.py:transition_state():463] send defer: 5
2022-11-22 19:16:55,660 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:55,660 INFO    HandlerThread:37629 [handler.py:handle_request_defer():162] handle defer: 5
2022-11-22 19:16:55,660 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:55,660 INFO    SenderThread:37629 [sender.py:send_request_defer():459] handle sender defer: 5
2022-11-22 19:16:56,291 INFO    Thread-17 :37629 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/wandb-summary.json
2022-11-22 19:16:56,292 INFO    Thread-17 :37629 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/output.log
2022-11-22 19:16:57,534 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:58,293 INFO    Thread-17 :37629 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/output.log
2022-11-22 19:17:01,127 INFO    SenderThread:37629 [sender.py:transition_state():463] send defer: 6
2022-11-22 19:17:01,127 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:17:01,127 INFO    HandlerThread:37629 [handler.py:handle_request_defer():162] handle defer: 6
2022-11-22 19:17:01,128 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: defer
2022-11-22 19:17:01,128 INFO    SenderThread:37629 [sender.py:send_request_defer():459] handle sender defer: 6
2022-11-22 19:17:01,297 INFO    Thread-17 :37629 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/config.yaml
2022-11-22 19:17:01,663 INFO    SenderThread:37629 [sender.py:transition_state():463] send defer: 7
2022-11-22 19:17:01,664 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:17:01,664 INFO    HandlerThread:37629 [handler.py:handle_request_defer():162] handle defer: 7
2022-11-22 19:17:01,664 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: defer
2022-11-22 19:17:01,664 INFO    SenderThread:37629 [sender.py:send_request_defer():459] handle sender defer: 7
2022-11-22 19:17:01,664 INFO    SenderThread:37629 [dir_watcher.py:finish():362] shutting down directory watcher
2022-11-22 19:17:02,298 INFO    Thread-17 :37629 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/output.log
2022-11-22 19:17:02,302 INFO    SenderThread:37629 [dir_watcher.py:finish():392] scan: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files
2022-11-22 19:17:02,303 INFO    SenderThread:37629 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/wandb-summary.json wandb-summary.json
2022-11-22 19:17:02,304 INFO    SenderThread:37629 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/config.yaml config.yaml
2022-11-22 19:17:02,305 INFO    SenderThread:37629 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/output.log output.log
2022-11-22 19:17:02,306 INFO    SenderThread:37629 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/requirements.txt requirements.txt
2022-11-22 19:17:02,306 INFO    SenderThread:37629 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/conda-environment.yaml conda-environment.yaml
2022-11-22 19:17:02,335 INFO    SenderThread:37629 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/wandb-metadata.json wandb-metadata.json
2022-11-22 19:17:02,336 INFO    SenderThread:37629 [sender.py:transition_state():463] send defer: 8
2022-11-22 19:17:02,361 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:17:02,367 INFO    HandlerThread:37629 [handler.py:handle_request_defer():162] handle defer: 8
2022-11-22 19:17:02,388 DEBUG   SenderThread:37629 [sender.py:send_request():317] send_request: defer
2022-11-22 19:17:02,389 INFO    SenderThread:37629 [sender.py:send_request_defer():459] handle sender defer: 8
2022-11-22 19:17:02,389 INFO    SenderThread:37629 [file_pusher.py:finish():168] shutting down file pusher
2022-11-22 19:17:02,546 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:07,549 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:12,554 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:15,671 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Wm79ZbWb0sgUqfwWHT8KKkE%2FmeAdT8ZKDBuu%2BN88RmPQYrvKj%2Fep3aqb41Nx2aCGr97HY65wVdN3rJIyOJ9cTiEWv3GhwgSWjJ16%2FK45KNI9%2FhXuu%2BlU4YxE5tgQjCSKN%2BuXP%2BmfVu16lsz24tYqKo6soS642dfE0wY91hhkvm%2Be89EW9Nm9dCgTkGTncqddNoSnW6leDMXaoY9O2u%2Fg3ACg2Skh6bVkB1En8CdSJDswsGB9U7o0nXUatMP715ZVSTAH0uAWALGNM7v%2FRtne3VpWJrWHopgSCxHYmMIOy3UsjAqoBlPXkdccRVIBvx2jFdmqKsQrR0t8ZtpN4oXjFQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Wm79ZbWb0sgUqfwWHT8KKkE%2FmeAdT8ZKDBuu%2BN88RmPQYrvKj%2Fep3aqb41Nx2aCGr97HY65wVdN3rJIyOJ9cTiEWv3GhwgSWjJ16%2FK45KNI9%2FhXuu%2BlU4YxE5tgQjCSKN%2BuXP%2BmfVu16lsz24tYqKo6soS642dfE0wY91hhkvm%2Be89EW9Nm9dCgTkGTncqddNoSnW6leDMXaoY9O2u%2Fg3ACg2Skh6bVkB1En8CdSJDswsGB9U7o0nXUatMP715ZVSTAH0uAWALGNM7v%2FRtne3VpWJrWHopgSCxHYmMIOy3UsjAqoBlPXkdccRVIBvx2jFdmqKsQrR0t8ZtpN4oXjFQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df81c6a30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:15,671 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2653'}
2022-11-22 19:17:15,672 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:17,557 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:22,561 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:26,712 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Wm79ZbWb0sgUqfwWHT8KKkE%2FmeAdT8ZKDBuu%2BN88RmPQYrvKj%2Fep3aqb41Nx2aCGr97HY65wVdN3rJIyOJ9cTiEWv3GhwgSWjJ16%2FK45KNI9%2FhXuu%2BlU4YxE5tgQjCSKN%2BuXP%2BmfVu16lsz24tYqKo6soS642dfE0wY91hhkvm%2Be89EW9Nm9dCgTkGTncqddNoSnW6leDMXaoY9O2u%2Fg3ACg2Skh6bVkB1En8CdSJDswsGB9U7o0nXUatMP715ZVSTAH0uAWALGNM7v%2FRtne3VpWJrWHopgSCxHYmMIOy3UsjAqoBlPXkdccRVIBvx2jFdmqKsQrR0t8ZtpN4oXjFQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Wm79ZbWb0sgUqfwWHT8KKkE%2FmeAdT8ZKDBuu%2BN88RmPQYrvKj%2Fep3aqb41Nx2aCGr97HY65wVdN3rJIyOJ9cTiEWv3GhwgSWjJ16%2FK45KNI9%2FhXuu%2BlU4YxE5tgQjCSKN%2BuXP%2BmfVu16lsz24tYqKo6soS642dfE0wY91hhkvm%2Be89EW9Nm9dCgTkGTncqddNoSnW6leDMXaoY9O2u%2Fg3ACg2Skh6bVkB1En8CdSJDswsGB9U7o0nXUatMP715ZVSTAH0uAWALGNM7v%2FRtne3VpWJrWHopgSCxHYmMIOy3UsjAqoBlPXkdccRVIBvx2jFdmqKsQrR0t8ZtpN4oXjFQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df8213f40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:26,712 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2653'}
2022-11-22 19:17:26,712 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:27,563 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:27,840 ERROR   Thread-21 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ae71Ppk2TGcgpZaO3aDq%2B00piT5lK7LD9mmmKSlBFDnuTg19P9qhlNeeY9Di2yZolSe8SnkV%2FnQprLRaABgF2VCQ0l%2BNVVqLQPcqhD60eaAKHWhb2jhLpx%2Fcw0NHoMPTKr2DAZ7XKfVgLlIsO1FEJisPOEjl3yiGCUc%2B1BD%2FnYie%2B1%2BM6Szf6G3A50ldK7r1zkx9KsnFcBJPXugYgzf9mAUODhqcjRVhkAZjndWTMwIZ%2B1YOR6dN1ZXIEP8RNha0yMQyRyVOkLoctXlR8qPBBmS3LOJV0QG6NkS9svwgzrgVfEpmCqjavJptCwhhwbC76LSLDd39QNgUVgX5d9AsOg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ae71Ppk2TGcgpZaO3aDq%2B00piT5lK7LD9mmmKSlBFDnuTg19P9qhlNeeY9Di2yZolSe8SnkV%2FnQprLRaABgF2VCQ0l%2BNVVqLQPcqhD60eaAKHWhb2jhLpx%2Fcw0NHoMPTKr2DAZ7XKfVgLlIsO1FEJisPOEjl3yiGCUc%2B1BD%2FnYie%2B1%2BM6Szf6G3A50ldK7r1zkx9KsnFcBJPXugYgzf9mAUODhqcjRVhkAZjndWTMwIZ%2B1YOR6dN1ZXIEP8RNha0yMQyRyVOkLoctXlR8qPBBmS3LOJV0QG6NkS9svwgzrgVfEpmCqjavJptCwhhwbC76LSLDd39QNgUVgX5d9AsOg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df81537c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:27,840 ERROR   Thread-21 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:17:27,840 ERROR   Thread-21 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:27,841 ERROR   Thread-23 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=LHJDpgaE1xtFRDAFd%2B9zW0wsf4M8PKdaWwk7imz%2B5F9stXq3NERn19NXn5NjENkkT2uA0AyzDougt3bqiRnR2XpEr2oMTNNCMRTqaF1xZ0ilCtfcwv7kwIpNazbT5P0uNgaJ8JbspCugdSJIM4IKm7IWEsbHXiKXCUwelkRSoZr1EANYkVChiK1xdARe%2BFn5VK2c7r6PsRmnLATByPpj3tjtYRGB9klzxWieHRQDfeMU4CAGTqBi7QtLoTwhwx8xscFolmHqfcMFv0%2FGhvXv8RWUQxYSDXOoCG0YaBw0TNI7jEgceumpQAamm7SQqqkHeCPfE2qQhVJm6vMFD%2BRh%2Fw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=LHJDpgaE1xtFRDAFd%2B9zW0wsf4M8PKdaWwk7imz%2B5F9stXq3NERn19NXn5NjENkkT2uA0AyzDougt3bqiRnR2XpEr2oMTNNCMRTqaF1xZ0ilCtfcwv7kwIpNazbT5P0uNgaJ8JbspCugdSJIM4IKm7IWEsbHXiKXCUwelkRSoZr1EANYkVChiK1xdARe%2BFn5VK2c7r6PsRmnLATByPpj3tjtYRGB9klzxWieHRQDfeMU4CAGTqBi7QtLoTwhwx8xscFolmHqfcMFv0%2FGhvXv8RWUQxYSDXOoCG0YaBw0TNI7jEgceumpQAamm7SQqqkHeCPfE2qQhVJm6vMFD%2BRh%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df8153730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:27,841 ERROR   Thread-23 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11206'}
2022-11-22 19:17:27,841 ERROR   Thread-23 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:27,995 ERROR   Thread-22 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ga3jqf6JeCJn0hKpEOjvTdXZZ4lOyLtmdp8x3RRXF4lMKwfYhlOEvRc%2FobwS4NNsMy71W4hGDkaLEhAMddXvlaPz2XSRhy26D4QOJUhPfszpAavD90sDmZN18P1HtzxM97R5V9wgtuMBjkm%2B3U3tn7kI%2B%2Bu2vwQUlGHaYq6K9R8NTnrtd3s%2FkFovSpmQ63DGQm%2FVD2s2dOs8dFpGnjbkechXkzbObtOSOG6oRyMgFQac7ZBag72oTgKVBB6%2BANRX4r07lk7E%2BAq3dujBMF6fPXmU5gDHIW51I1jvqQYPfEhvISZxtRNuEqFedhVE9hInmGqalszXREi%2FFAOvk3CocA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ga3jqf6JeCJn0hKpEOjvTdXZZ4lOyLtmdp8x3RRXF4lMKwfYhlOEvRc%2FobwS4NNsMy71W4hGDkaLEhAMddXvlaPz2XSRhy26D4QOJUhPfszpAavD90sDmZN18P1HtzxM97R5V9wgtuMBjkm%2B3U3tn7kI%2B%2Bu2vwQUlGHaYq6K9R8NTnrtd3s%2FkFovSpmQ63DGQm%2FVD2s2dOs8dFpGnjbkechXkzbObtOSOG6oRyMgFQac7ZBag72oTgKVBB6%2BANRX4r07lk7E%2BAq3dujBMF6fPXmU5gDHIW51I1jvqQYPfEhvISZxtRNuEqFedhVE9hInmGqalszXREi%2FFAOvk3CocA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df0142250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:27,995 ERROR   Thread-22 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:17:27,996 ERROR   Thread-22 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:28,006 ERROR   Thread-25 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KHlZP1cC6q197Wrs6%2B%2F4bKGydstjzXH8uoUHKmAWjQPNrV4PDuedd0eKW1%2F4cWy%2B9todieOKt2WfHYbL1KvUHr5jiny9A8GwHGVWMsTZMG3LobduzzJfYwGHrpdiNVnYbH9xb2OF5YwAZQ1NeG6VB7vQKWs8Vq1Qu%2BnzL5HMkn9zT9ZN0kgefHIY4QTgtyMo0MZ7rQW0nluiuC9Fvz8yiCHzTThpEgPJA%2F2s24droCntWkCFYn575PeCVK8DiqA4iS1eUv5ae1cROSXwWRBW%2FT2fvetCEeFf%2BhRq%2BxU7CGxqDwfmOXMONmXsgg7W7B4SpcLZiMSL%2BnC6ujHrXkcVOg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KHlZP1cC6q197Wrs6%2B%2F4bKGydstjzXH8uoUHKmAWjQPNrV4PDuedd0eKW1%2F4cWy%2B9todieOKt2WfHYbL1KvUHr5jiny9A8GwHGVWMsTZMG3LobduzzJfYwGHrpdiNVnYbH9xb2OF5YwAZQ1NeG6VB7vQKWs8Vq1Qu%2BnzL5HMkn9zT9ZN0kgefHIY4QTgtyMo0MZ7rQW0nluiuC9Fvz8yiCHzTThpEgPJA%2F2s24droCntWkCFYn575PeCVK8DiqA4iS1eUv5ae1cROSXwWRBW%2FT2fvetCEeFf%2BhRq%2BxU7CGxqDwfmOXMONmXsgg7W7B4SpcLZiMSL%2BnC6ujHrXkcVOg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df0142fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:28,006 ERROR   Thread-25 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:17:28,006 ERROR   Thread-25 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:28,074 ERROR   Thread-24 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QujgpVfC%2B6eC7pVyjgp%2Bfq726Km36AinDsnTsevbeLeYmq7gmf%2Fk%2FutaDCnxStiw5iP%2BWzPt7oO31FhIagpfKx6Y1skvhDezKgr48gFPrxPQXAjV0Q9FcRsEXP5HRpZ85Cwgd%2BK9%2BTQnONELdsQBh%2BUUHJawAn1KsSDRyUXLX6mfdhP3uywXAVtbH9NCpor22oZyzkPG16Nhqw8d3KOybO0P5OfUfSqmrQXokiSwyRoj5BTNvi1ez8MzwhSq7%2B6BE%2Bs90%2FKMjHmklLoqPruBdmhKWZtuZXaZoopK9c3yxxx5KZa1H7MZ%2BQINJCkONu2qQjMhpFXYQgTDUkUH%2BTlzjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QujgpVfC%2B6eC7pVyjgp%2Bfq726Km36AinDsnTsevbeLeYmq7gmf%2Fk%2FutaDCnxStiw5iP%2BWzPt7oO31FhIagpfKx6Y1skvhDezKgr48gFPrxPQXAjV0Q9FcRsEXP5HRpZ85Cwgd%2BK9%2BTQnONELdsQBh%2BUUHJawAn1KsSDRyUXLX6mfdhP3uywXAVtbH9NCpor22oZyzkPG16Nhqw8d3KOybO0P5OfUfSqmrQXokiSwyRoj5BTNvi1ez8MzwhSq7%2B6BE%2Bs90%2FKMjHmklLoqPruBdmhKWZtuZXaZoopK9c3yxxx5KZa1H7MZ%2BQINJCkONu2qQjMhpFXYQgTDUkUH%2BTlzjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df01420a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:28,074 ERROR   Thread-24 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:17:28,075 ERROR   Thread-24 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:32,567 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:37,570 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:38,903 ERROR   Thread-21 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ae71Ppk2TGcgpZaO3aDq%2B00piT5lK7LD9mmmKSlBFDnuTg19P9qhlNeeY9Di2yZolSe8SnkV%2FnQprLRaABgF2VCQ0l%2BNVVqLQPcqhD60eaAKHWhb2jhLpx%2Fcw0NHoMPTKr2DAZ7XKfVgLlIsO1FEJisPOEjl3yiGCUc%2B1BD%2FnYie%2B1%2BM6Szf6G3A50ldK7r1zkx9KsnFcBJPXugYgzf9mAUODhqcjRVhkAZjndWTMwIZ%2B1YOR6dN1ZXIEP8RNha0yMQyRyVOkLoctXlR8qPBBmS3LOJV0QG6NkS9svwgzrgVfEpmCqjavJptCwhhwbC76LSLDd39QNgUVgX5d9AsOg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ae71Ppk2TGcgpZaO3aDq%2B00piT5lK7LD9mmmKSlBFDnuTg19P9qhlNeeY9Di2yZolSe8SnkV%2FnQprLRaABgF2VCQ0l%2BNVVqLQPcqhD60eaAKHWhb2jhLpx%2Fcw0NHoMPTKr2DAZ7XKfVgLlIsO1FEJisPOEjl3yiGCUc%2B1BD%2FnYie%2B1%2BM6Szf6G3A50ldK7r1zkx9KsnFcBJPXugYgzf9mAUODhqcjRVhkAZjndWTMwIZ%2B1YOR6dN1ZXIEP8RNha0yMQyRyVOkLoctXlR8qPBBmS3LOJV0QG6NkS9svwgzrgVfEpmCqjavJptCwhhwbC76LSLDd39QNgUVgX5d9AsOg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df013b0a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:38,903 ERROR   Thread-21 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:17:38,903 ERROR   Thread-21 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:38,991 ERROR   Thread-23 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=LHJDpgaE1xtFRDAFd%2B9zW0wsf4M8PKdaWwk7imz%2B5F9stXq3NERn19NXn5NjENkkT2uA0AyzDougt3bqiRnR2XpEr2oMTNNCMRTqaF1xZ0ilCtfcwv7kwIpNazbT5P0uNgaJ8JbspCugdSJIM4IKm7IWEsbHXiKXCUwelkRSoZr1EANYkVChiK1xdARe%2BFn5VK2c7r6PsRmnLATByPpj3tjtYRGB9klzxWieHRQDfeMU4CAGTqBi7QtLoTwhwx8xscFolmHqfcMFv0%2FGhvXv8RWUQxYSDXOoCG0YaBw0TNI7jEgceumpQAamm7SQqqkHeCPfE2qQhVJm6vMFD%2BRh%2Fw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=LHJDpgaE1xtFRDAFd%2B9zW0wsf4M8PKdaWwk7imz%2B5F9stXq3NERn19NXn5NjENkkT2uA0AyzDougt3bqiRnR2XpEr2oMTNNCMRTqaF1xZ0ilCtfcwv7kwIpNazbT5P0uNgaJ8JbspCugdSJIM4IKm7IWEsbHXiKXCUwelkRSoZr1EANYkVChiK1xdARe%2BFn5VK2c7r6PsRmnLATByPpj3tjtYRGB9klzxWieHRQDfeMU4CAGTqBi7QtLoTwhwx8xscFolmHqfcMFv0%2FGhvXv8RWUQxYSDXOoCG0YaBw0TNI7jEgceumpQAamm7SQqqkHeCPfE2qQhVJm6vMFD%2BRh%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df8172be0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:38,991 ERROR   Thread-23 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11206'}
2022-11-22 19:17:38,991 ERROR   Thread-23 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:39,027 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Wm79ZbWb0sgUqfwWHT8KKkE%2FmeAdT8ZKDBuu%2BN88RmPQYrvKj%2Fep3aqb41Nx2aCGr97HY65wVdN3rJIyOJ9cTiEWv3GhwgSWjJ16%2FK45KNI9%2FhXuu%2BlU4YxE5tgQjCSKN%2BuXP%2BmfVu16lsz24tYqKo6soS642dfE0wY91hhkvm%2Be89EW9Nm9dCgTkGTncqddNoSnW6leDMXaoY9O2u%2Fg3ACg2Skh6bVkB1En8CdSJDswsGB9U7o0nXUatMP715ZVSTAH0uAWALGNM7v%2FRtne3VpWJrWHopgSCxHYmMIOy3UsjAqoBlPXkdccRVIBvx2jFdmqKsQrR0t8ZtpN4oXjFQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Wm79ZbWb0sgUqfwWHT8KKkE%2FmeAdT8ZKDBuu%2BN88RmPQYrvKj%2Fep3aqb41Nx2aCGr97HY65wVdN3rJIyOJ9cTiEWv3GhwgSWjJ16%2FK45KNI9%2FhXuu%2BlU4YxE5tgQjCSKN%2BuXP%2BmfVu16lsz24tYqKo6soS642dfE0wY91hhkvm%2Be89EW9Nm9dCgTkGTncqddNoSnW6leDMXaoY9O2u%2Fg3ACg2Skh6bVkB1En8CdSJDswsGB9U7o0nXUatMP715ZVSTAH0uAWALGNM7v%2FRtne3VpWJrWHopgSCxHYmMIOy3UsjAqoBlPXkdccRVIBvx2jFdmqKsQrR0t8ZtpN4oXjFQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df01559d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:39,027 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2653'}
2022-11-22 19:17:39,027 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:39,182 ERROR   Thread-22 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ga3jqf6JeCJn0hKpEOjvTdXZZ4lOyLtmdp8x3RRXF4lMKwfYhlOEvRc%2FobwS4NNsMy71W4hGDkaLEhAMddXvlaPz2XSRhy26D4QOJUhPfszpAavD90sDmZN18P1HtzxM97R5V9wgtuMBjkm%2B3U3tn7kI%2B%2Bu2vwQUlGHaYq6K9R8NTnrtd3s%2FkFovSpmQ63DGQm%2FVD2s2dOs8dFpGnjbkechXkzbObtOSOG6oRyMgFQac7ZBag72oTgKVBB6%2BANRX4r07lk7E%2BAq3dujBMF6fPXmU5gDHIW51I1jvqQYPfEhvISZxtRNuEqFedhVE9hInmGqalszXREi%2FFAOvk3CocA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ga3jqf6JeCJn0hKpEOjvTdXZZ4lOyLtmdp8x3RRXF4lMKwfYhlOEvRc%2FobwS4NNsMy71W4hGDkaLEhAMddXvlaPz2XSRhy26D4QOJUhPfszpAavD90sDmZN18P1HtzxM97R5V9wgtuMBjkm%2B3U3tn7kI%2B%2Bu2vwQUlGHaYq6K9R8NTnrtd3s%2FkFovSpmQ63DGQm%2FVD2s2dOs8dFpGnjbkechXkzbObtOSOG6oRyMgFQac7ZBag72oTgKVBB6%2BANRX4r07lk7E%2BAq3dujBMF6fPXmU5gDHIW51I1jvqQYPfEhvISZxtRNuEqFedhVE9hInmGqalszXREi%2FFAOvk3CocA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df0142f40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:39,182 ERROR   Thread-22 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:17:39,182 ERROR   Thread-22 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:39,254 ERROR   Thread-25 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KHlZP1cC6q197Wrs6%2B%2F4bKGydstjzXH8uoUHKmAWjQPNrV4PDuedd0eKW1%2F4cWy%2B9todieOKt2WfHYbL1KvUHr5jiny9A8GwHGVWMsTZMG3LobduzzJfYwGHrpdiNVnYbH9xb2OF5YwAZQ1NeG6VB7vQKWs8Vq1Qu%2BnzL5HMkn9zT9ZN0kgefHIY4QTgtyMo0MZ7rQW0nluiuC9Fvz8yiCHzTThpEgPJA%2F2s24droCntWkCFYn575PeCVK8DiqA4iS1eUv5ae1cROSXwWRBW%2FT2fvetCEeFf%2BhRq%2BxU7CGxqDwfmOXMONmXsgg7W7B4SpcLZiMSL%2BnC6ujHrXkcVOg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KHlZP1cC6q197Wrs6%2B%2F4bKGydstjzXH8uoUHKmAWjQPNrV4PDuedd0eKW1%2F4cWy%2B9todieOKt2WfHYbL1KvUHr5jiny9A8GwHGVWMsTZMG3LobduzzJfYwGHrpdiNVnYbH9xb2OF5YwAZQ1NeG6VB7vQKWs8Vq1Qu%2BnzL5HMkn9zT9ZN0kgefHIY4QTgtyMo0MZ7rQW0nluiuC9Fvz8yiCHzTThpEgPJA%2F2s24droCntWkCFYn575PeCVK8DiqA4iS1eUv5ae1cROSXwWRBW%2FT2fvetCEeFf%2BhRq%2BxU7CGxqDwfmOXMONmXsgg7W7B4SpcLZiMSL%2BnC6ujHrXkcVOg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df815c370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:39,254 ERROR   Thread-25 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:17:39,254 ERROR   Thread-25 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:39,268 ERROR   Thread-24 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QujgpVfC%2B6eC7pVyjgp%2Bfq726Km36AinDsnTsevbeLeYmq7gmf%2Fk%2FutaDCnxStiw5iP%2BWzPt7oO31FhIagpfKx6Y1skvhDezKgr48gFPrxPQXAjV0Q9FcRsEXP5HRpZ85Cwgd%2BK9%2BTQnONELdsQBh%2BUUHJawAn1KsSDRyUXLX6mfdhP3uywXAVtbH9NCpor22oZyzkPG16Nhqw8d3KOybO0P5OfUfSqmrQXokiSwyRoj5BTNvi1ez8MzwhSq7%2B6BE%2Bs90%2FKMjHmklLoqPruBdmhKWZtuZXaZoopK9c3yxxx5KZa1H7MZ%2BQINJCkONu2qQjMhpFXYQgTDUkUH%2BTlzjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QujgpVfC%2B6eC7pVyjgp%2Bfq726Km36AinDsnTsevbeLeYmq7gmf%2Fk%2FutaDCnxStiw5iP%2BWzPt7oO31FhIagpfKx6Y1skvhDezKgr48gFPrxPQXAjV0Q9FcRsEXP5HRpZ85Cwgd%2BK9%2BTQnONELdsQBh%2BUUHJawAn1KsSDRyUXLX6mfdhP3uywXAVtbH9NCpor22oZyzkPG16Nhqw8d3KOybO0P5OfUfSqmrQXokiSwyRoj5BTNvi1ez8MzwhSq7%2B6BE%2Bs90%2FKMjHmklLoqPruBdmhKWZtuZXaZoopK9c3yxxx5KZa1H7MZ%2BQINJCkONu2qQjMhpFXYQgTDUkUH%2BTlzjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df818f9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:39,268 ERROR   Thread-24 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:17:39,268 ERROR   Thread-24 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:42,572 DEBUG   HandlerThread:37629 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:48,712 WARNING StreamThr :37629 [internal.py:is_dead():385] Internal process exiting, parent pid 37528 disappeared
2022-11-22 19:17:48,712 ERROR   StreamThr :37629 [internal.py:wandb_internal():147] Internal process shutdown.
2022-11-22 19:17:49,399 INFO    SenderThread:37629 [sender.py:finish():1331] shutting down sender
2022-11-22 19:17:49,399 INFO    SenderThread:37629 [file_pusher.py:finish():168] shutting down file pusher
2022-11-22 19:17:49,399 INFO    SenderThread:37629 [file_pusher.py:join():173] waiting for file pusher
2022-11-22 19:17:49,580 INFO    HandlerThread:37629 [handler.py:finish():814] shutting down handler
2022-11-22 19:17:49,675 INFO    WriterThread:37629 [datastore.py:close():279] close: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/run-3gudo1hi.wandb
2022-11-22 19:17:51,135 ERROR   Thread-23 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=LHJDpgaE1xtFRDAFd%2B9zW0wsf4M8PKdaWwk7imz%2B5F9stXq3NERn19NXn5NjENkkT2uA0AyzDougt3bqiRnR2XpEr2oMTNNCMRTqaF1xZ0ilCtfcwv7kwIpNazbT5P0uNgaJ8JbspCugdSJIM4IKm7IWEsbHXiKXCUwelkRSoZr1EANYkVChiK1xdARe%2BFn5VK2c7r6PsRmnLATByPpj3tjtYRGB9klzxWieHRQDfeMU4CAGTqBi7QtLoTwhwx8xscFolmHqfcMFv0%2FGhvXv8RWUQxYSDXOoCG0YaBw0TNI7jEgceumpQAamm7SQqqkHeCPfE2qQhVJm6vMFD%2BRh%2Fw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=LHJDpgaE1xtFRDAFd%2B9zW0wsf4M8PKdaWwk7imz%2B5F9stXq3NERn19NXn5NjENkkT2uA0AyzDougt3bqiRnR2XpEr2oMTNNCMRTqaF1xZ0ilCtfcwv7kwIpNazbT5P0uNgaJ8JbspCugdSJIM4IKm7IWEsbHXiKXCUwelkRSoZr1EANYkVChiK1xdARe%2BFn5VK2c7r6PsRmnLATByPpj3tjtYRGB9klzxWieHRQDfeMU4CAGTqBi7QtLoTwhwx8xscFolmHqfcMFv0%2FGhvXv8RWUQxYSDXOoCG0YaBw0TNI7jEgceumpQAamm7SQqqkHeCPfE2qQhVJm6vMFD%2BRh%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df82e3400>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,135 ERROR   Thread-23 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11206'}
2022-11-22 19:17:51,135 ERROR   Thread-23 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:51,142 ERROR   Thread-21 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ae71Ppk2TGcgpZaO3aDq%2B00piT5lK7LD9mmmKSlBFDnuTg19P9qhlNeeY9Di2yZolSe8SnkV%2FnQprLRaABgF2VCQ0l%2BNVVqLQPcqhD60eaAKHWhb2jhLpx%2Fcw0NHoMPTKr2DAZ7XKfVgLlIsO1FEJisPOEjl3yiGCUc%2B1BD%2FnYie%2B1%2BM6Szf6G3A50ldK7r1zkx9KsnFcBJPXugYgzf9mAUODhqcjRVhkAZjndWTMwIZ%2B1YOR6dN1ZXIEP8RNha0yMQyRyVOkLoctXlR8qPBBmS3LOJV0QG6NkS9svwgzrgVfEpmCqjavJptCwhhwbC76LSLDd39QNgUVgX5d9AsOg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ae71Ppk2TGcgpZaO3aDq%2B00piT5lK7LD9mmmKSlBFDnuTg19P9qhlNeeY9Di2yZolSe8SnkV%2FnQprLRaABgF2VCQ0l%2BNVVqLQPcqhD60eaAKHWhb2jhLpx%2Fcw0NHoMPTKr2DAZ7XKfVgLlIsO1FEJisPOEjl3yiGCUc%2B1BD%2FnYie%2B1%2BM6Szf6G3A50ldK7r1zkx9KsnFcBJPXugYgzf9mAUODhqcjRVhkAZjndWTMwIZ%2B1YOR6dN1ZXIEP8RNha0yMQyRyVOkLoctXlR8qPBBmS3LOJV0QG6NkS9svwgzrgVfEpmCqjavJptCwhhwbC76LSLDd39QNgUVgX5d9AsOg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df81c6af0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,142 ERROR   Thread-21 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:17:51,142 ERROR   Thread-21 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:51,379 ERROR   Thread-25 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KHlZP1cC6q197Wrs6%2B%2F4bKGydstjzXH8uoUHKmAWjQPNrV4PDuedd0eKW1%2F4cWy%2B9todieOKt2WfHYbL1KvUHr5jiny9A8GwHGVWMsTZMG3LobduzzJfYwGHrpdiNVnYbH9xb2OF5YwAZQ1NeG6VB7vQKWs8Vq1Qu%2BnzL5HMkn9zT9ZN0kgefHIY4QTgtyMo0MZ7rQW0nluiuC9Fvz8yiCHzTThpEgPJA%2F2s24droCntWkCFYn575PeCVK8DiqA4iS1eUv5ae1cROSXwWRBW%2FT2fvetCEeFf%2BhRq%2BxU7CGxqDwfmOXMONmXsgg7W7B4SpcLZiMSL%2BnC6ujHrXkcVOg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KHlZP1cC6q197Wrs6%2B%2F4bKGydstjzXH8uoUHKmAWjQPNrV4PDuedd0eKW1%2F4cWy%2B9todieOKt2WfHYbL1KvUHr5jiny9A8GwHGVWMsTZMG3LobduzzJfYwGHrpdiNVnYbH9xb2OF5YwAZQ1NeG6VB7vQKWs8Vq1Qu%2BnzL5HMkn9zT9ZN0kgefHIY4QTgtyMo0MZ7rQW0nluiuC9Fvz8yiCHzTThpEgPJA%2F2s24droCntWkCFYn575PeCVK8DiqA4iS1eUv5ae1cROSXwWRBW%2FT2fvetCEeFf%2BhRq%2BxU7CGxqDwfmOXMONmXsgg7W7B4SpcLZiMSL%2BnC6ujHrXkcVOg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df8172310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,380 ERROR   Thread-25 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:17:51,380 ERROR   Thread-25 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:51,398 ERROR   Thread-22 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ga3jqf6JeCJn0hKpEOjvTdXZZ4lOyLtmdp8x3RRXF4lMKwfYhlOEvRc%2FobwS4NNsMy71W4hGDkaLEhAMddXvlaPz2XSRhy26D4QOJUhPfszpAavD90sDmZN18P1HtzxM97R5V9wgtuMBjkm%2B3U3tn7kI%2B%2Bu2vwQUlGHaYq6K9R8NTnrtd3s%2FkFovSpmQ63DGQm%2FVD2s2dOs8dFpGnjbkechXkzbObtOSOG6oRyMgFQac7ZBag72oTgKVBB6%2BANRX4r07lk7E%2BAq3dujBMF6fPXmU5gDHIW51I1jvqQYPfEhvISZxtRNuEqFedhVE9hInmGqalszXREi%2FFAOvk3CocA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ga3jqf6JeCJn0hKpEOjvTdXZZ4lOyLtmdp8x3RRXF4lMKwfYhlOEvRc%2FobwS4NNsMy71W4hGDkaLEhAMddXvlaPz2XSRhy26D4QOJUhPfszpAavD90sDmZN18P1HtzxM97R5V9wgtuMBjkm%2B3U3tn7kI%2B%2Bu2vwQUlGHaYq6K9R8NTnrtd3s%2FkFovSpmQ63DGQm%2FVD2s2dOs8dFpGnjbkechXkzbObtOSOG6oRyMgFQac7ZBag72oTgKVBB6%2BANRX4r07lk7E%2BAq3dujBMF6fPXmU5gDHIW51I1jvqQYPfEhvISZxtRNuEqFedhVE9hInmGqalszXREi%2FFAOvk3CocA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df013bac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,399 ERROR   Thread-22 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:17:51,399 ERROR   Thread-22 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:51,683 ERROR   Thread-24 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QujgpVfC%2B6eC7pVyjgp%2Bfq726Km36AinDsnTsevbeLeYmq7gmf%2Fk%2FutaDCnxStiw5iP%2BWzPt7oO31FhIagpfKx6Y1skvhDezKgr48gFPrxPQXAjV0Q9FcRsEXP5HRpZ85Cwgd%2BK9%2BTQnONELdsQBh%2BUUHJawAn1KsSDRyUXLX6mfdhP3uywXAVtbH9NCpor22oZyzkPG16Nhqw8d3KOybO0P5OfUfSqmrQXokiSwyRoj5BTNvi1ez8MzwhSq7%2B6BE%2Bs90%2FKMjHmklLoqPruBdmhKWZtuZXaZoopK9c3yxxx5KZa1H7MZ%2BQINJCkONu2qQjMhpFXYQgTDUkUH%2BTlzjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QujgpVfC%2B6eC7pVyjgp%2Bfq726Km36AinDsnTsevbeLeYmq7gmf%2Fk%2FutaDCnxStiw5iP%2BWzPt7oO31FhIagpfKx6Y1skvhDezKgr48gFPrxPQXAjV0Q9FcRsEXP5HRpZ85Cwgd%2BK9%2BTQnONELdsQBh%2BUUHJawAn1KsSDRyUXLX6mfdhP3uywXAVtbH9NCpor22oZyzkPG16Nhqw8d3KOybO0P5OfUfSqmrQXokiSwyRoj5BTNvi1ez8MzwhSq7%2B6BE%2Bs90%2FKMjHmklLoqPruBdmhKWZtuZXaZoopK9c3yxxx5KZa1H7MZ%2BQINJCkONu2qQjMhpFXYQgTDUkUH%2BTlzjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df83e0940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,683 ERROR   Thread-24 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:17:51,683 ERROR   Thread-24 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:53,826 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Wm79ZbWb0sgUqfwWHT8KKkE%2FmeAdT8ZKDBuu%2BN88RmPQYrvKj%2Fep3aqb41Nx2aCGr97HY65wVdN3rJIyOJ9cTiEWv3GhwgSWjJ16%2FK45KNI9%2FhXuu%2BlU4YxE5tgQjCSKN%2BuXP%2BmfVu16lsz24tYqKo6soS642dfE0wY91hhkvm%2Be89EW9Nm9dCgTkGTncqddNoSnW6leDMXaoY9O2u%2Fg3ACg2Skh6bVkB1En8CdSJDswsGB9U7o0nXUatMP715ZVSTAH0uAWALGNM7v%2FRtne3VpWJrWHopgSCxHYmMIOy3UsjAqoBlPXkdccRVIBvx2jFdmqKsQrR0t8ZtpN4oXjFQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3gudo1hi/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Wm79ZbWb0sgUqfwWHT8KKkE%2FmeAdT8ZKDBuu%2BN88RmPQYrvKj%2Fep3aqb41Nx2aCGr97HY65wVdN3rJIyOJ9cTiEWv3GhwgSWjJ16%2FK45KNI9%2FhXuu%2BlU4YxE5tgQjCSKN%2BuXP%2BmfVu16lsz24tYqKo6soS642dfE0wY91hhkvm%2Be89EW9Nm9dCgTkGTncqddNoSnW6leDMXaoY9O2u%2Fg3ACg2Skh6bVkB1En8CdSJDswsGB9U7o0nXUatMP715ZVSTAH0uAWALGNM7v%2FRtne3VpWJrWHopgSCxHYmMIOy3UsjAqoBlPXkdccRVIBvx2jFdmqKsQrR0t8ZtpN4oXjFQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3df818f790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:53,826 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2653'}
2022-11-22 19:17:53,827 ERROR   Thread-20 :37629 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:59,311 INFO    Thread-24 :37629 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/requirements.txt
2022-11-22 19:17:59,321 INFO    Thread-22 :37629 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/config.yaml
2022-11-22 19:17:59,324 INFO    Thread-21 :37629 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/wandb-summary.json
2022-11-22 19:17:59,381 INFO    Thread-23 :37629 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/output.log
2022-11-22 19:17:59,875 INFO    Thread-25 :37629 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3gudo1hi/files/conda-environment.yaml
2022-11-22 19:18:02,487 INFO    Thread-20 :37629 [upload_job.py:push():143] Uploaded file /tmp/tmpxpb91sepwandb/2xblz9sg-wandb-metadata.json
2022-11-22 19:18:02,688 INFO    Thread-16 :37629 [sender.py:transition_state():463] send defer: 9
