2022-11-22 19:16:19,693 INFO    StreamThr :37625 [internal.py:wandb_internal():88] W&B internal server running at pid: 37625, started at: 2022-11-22 19:16:19.692547
2022-11-22 19:16:19,695 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: status
2022-11-22 19:16:19,697 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: status
2022-11-22 19:16:19,699 INFO    WriterThread:37625 [datastore.py:open_for_write():75] open: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/run-3epim9cz.wandb
2022-11-22 19:16:19,700 DEBUG   SenderThread:37625 [sender.py:send():303] send: header
2022-11-22 19:16:19,700 DEBUG   SenderThread:37625 [sender.py:send():303] send: run
2022-11-22 19:16:19,720 INFO    SenderThread:37625 [sender.py:_maybe_setup_resume():593] checking resume status for None/YOLOR/3epim9cz
2022-11-22 19:16:24,699 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:29,702 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:34,704 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:39,707 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:44,711 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:46,125 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: check_version
2022-11-22 19:16:46,126 INFO    SenderThread:37625 [dir_watcher.py:__init__():216] watching files in: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files
2022-11-22 19:16:46,127 INFO    SenderThread:37625 [sender.py:_start_run_threads():928] run started: 3epim9cz with start time 1669115779.688696
2022-11-22 19:16:46,127 DEBUG   SenderThread:37625 [sender.py:send():303] send: summary
2022-11-22 19:16:46,127 INFO    SenderThread:37625 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:16:46,127 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: check_version
2022-11-22 19:16:47,144 INFO    Thread-17 :37625 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/wandb-summary.json
2022-11-22 19:16:47,817 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: run_start
2022-11-22 19:16:47,819 DEBUG   HandlerThread:37625 [system_info.py:__init__():31] System info init
2022-11-22 19:16:47,819 DEBUG   HandlerThread:37625 [system_info.py:__init__():46] System info init done
2022-11-22 19:16:47,820 INFO    HandlerThread:37625 [system_monitor.py:start():150] Starting system monitor
2022-11-22 19:16:47,820 INFO    SystemMonitor:37625 [system_monitor.py:_start():116] Starting system asset monitoring threads
2022-11-22 19:16:47,820 INFO    HandlerThread:37625 [system_monitor.py:probe():168] Collecting system info
2022-11-22 19:16:47,821 INFO    SystemMonitor:37625 [interfaces.py:start():168] Started cpu
2022-11-22 19:16:47,822 INFO    SystemMonitor:37625 [interfaces.py:start():168] Started disk
2022-11-22 19:16:47,823 INFO    SystemMonitor:37625 [interfaces.py:start():168] Started gpu
2022-11-22 19:16:47,823 INFO    SystemMonitor:37625 [interfaces.py:start():168] Started memory
2022-11-22 19:16:47,824 INFO    SystemMonitor:37625 [interfaces.py:start():168] Started network
2022-11-22 19:16:47,846 DEBUG   HandlerThread:37625 [system_info.py:probe():195] Probing system
2022-11-22 19:16:47,850 DEBUG   HandlerThread:37625 [git.py:repo():40] git repository is invalid
2022-11-22 19:16:47,850 DEBUG   HandlerThread:37625 [system_info.py:probe():241] Probing system done
2022-11-22 19:16:47,850 DEBUG   HandlerThread:37625 [system_monitor.py:probe():177] {'os': 'Linux-5.15.0-53-generic-x86_64-with-glibc2.17', 'python': '3.8.13', 'heartbeatAt': '2022-11-22T11:16:47.846968', 'startedAt': '2022-11-22T11:16:19.679614', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/rp/DeepLearning/yolov7-main/train.py', 'codePath': 'train.py', 'host': 'rp', 'username': 'rp', 'executable': '/home/rp/Softwares/anaconda3/envs/dyh/bin/python', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3120.243, 'min': 800.0, 'max': 4800.0}, 'cpu_freq_per_core': [{'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 4655.134, 'min': 800.0, 'max': 4800.0}, {'current': 4668.754, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}], 'disk': {'total': 937.3305015563965, 'used': 300.8215675354004}, 'gpu': 'NVIDIA GeForce RTX 3080', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10497294336}], 'memory': {'total': 31.272598266601562}}
2022-11-22 19:16:47,850 INFO    HandlerThread:37625 [system_monitor.py:probe():178] Finished collecting system info
2022-11-22 19:16:47,850 INFO    HandlerThread:37625 [system_monitor.py:probe():181] Publishing system info
2022-11-22 19:16:47,850 DEBUG   HandlerThread:37625 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2022-11-22 19:16:47,852 DEBUG   HandlerThread:37625 [system_info.py:_save_pip():67] Saving pip packages done
2022-11-22 19:16:47,852 DEBUG   HandlerThread:37625 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2022-11-22 19:16:48,133 INFO    Thread-17 :37625 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/conda-environment.yaml
2022-11-22 19:16:48,133 INFO    Thread-17 :37625 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/requirements.txt
2022-11-22 19:16:50,314 DEBUG   HandlerThread:37625 [system_info.py:_save_conda():86] Saving conda packages done
2022-11-22 19:16:50,321 INFO    HandlerThread:37625 [system_monitor.py:probe():183] Finished publishing system info
2022-11-22 19:16:50,361 DEBUG   SenderThread:37625 [sender.py:send():303] send: files
2022-11-22 19:16:50,361 INFO    SenderThread:37625 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-11-22 19:16:50,371 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: stop_status
2022-11-22 19:16:50,372 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: stop_status
2022-11-22 19:16:51,134 INFO    Thread-17 :37625 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/conda-environment.yaml
2022-11-22 19:16:51,134 INFO    Thread-17 :37625 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/wandb-metadata.json
2022-11-22 19:16:52,842 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: poll_exit
2022-11-22 19:16:56,011 DEBUG   SenderThread:37625 [sender.py:send():303] send: telemetry
2022-11-22 19:16:56,012 DEBUG   SenderThread:37625 [sender.py:send():303] send: telemetry
2022-11-22 19:16:56,012 DEBUG   SenderThread:37625 [sender.py:send():303] send: config
2022-11-22 19:16:56,012 DEBUG   SenderThread:37625 [sender.py:send():303] send: config
2022-11-22 19:16:56,016 DEBUG   SenderThread:37625 [sender.py:send():303] send: exit
2022-11-22 19:16:56,017 INFO    SenderThread:37625 [sender.py:send_exit():442] handling exit code: 0
2022-11-22 19:16:56,017 INFO    SenderThread:37625 [sender.py:send_exit():444] handling runtime: 4
2022-11-22 19:16:56,017 INFO    SenderThread:37625 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:16:56,018 INFO    SenderThread:37625 [sender.py:send_exit():450] send defer
2022-11-22 19:16:56,018 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: poll_exit
2022-11-22 19:16:56,018 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,018 INFO    HandlerThread:37625 [handler.py:handle_request_defer():162] handle defer: 0
2022-11-22 19:16:56,019 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,019 INFO    SenderThread:37625 [sender.py:send_request_defer():459] handle sender defer: 0
2022-11-22 19:16:56,019 INFO    SenderThread:37625 [sender.py:transition_state():463] send defer: 1
2022-11-22 19:16:56,019 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,019 INFO    HandlerThread:37625 [handler.py:handle_request_defer():162] handle defer: 1
2022-11-22 19:16:56,019 INFO    HandlerThread:37625 [system_monitor.py:finish():160] Stopping system monitor
2022-11-22 19:16:56,019 DEBUG   SystemMonitor:37625 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2022-11-22 19:16:56,020 DEBUG   SystemMonitor:37625 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2022-11-22 19:16:56,021 INFO    HandlerThread:37625 [interfaces.py:finish():173] Joined cpu
2022-11-22 19:16:56,021 DEBUG   SystemMonitor:37625 [system_monitor.py:_start():141] Publishing last batch of metrics
2022-11-22 19:16:56,021 INFO    HandlerThread:37625 [interfaces.py:finish():173] Joined disk
2022-11-22 19:16:56,069 INFO    HandlerThread:37625 [interfaces.py:finish():173] Joined gpu
2022-11-22 19:16:56,069 INFO    HandlerThread:37625 [interfaces.py:finish():173] Joined memory
2022-11-22 19:16:56,070 INFO    HandlerThread:37625 [interfaces.py:finish():173] Joined network
2022-11-22 19:16:56,070 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,070 INFO    SenderThread:37625 [sender.py:send_request_defer():459] handle sender defer: 1
2022-11-22 19:16:56,070 INFO    SenderThread:37625 [sender.py:transition_state():463] send defer: 2
2022-11-22 19:16:56,070 DEBUG   SenderThread:37625 [sender.py:send():303] send: stats
2022-11-22 19:16:56,071 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,071 INFO    HandlerThread:37625 [handler.py:handle_request_defer():162] handle defer: 2
2022-11-22 19:16:56,071 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,071 INFO    SenderThread:37625 [sender.py:send_request_defer():459] handle sender defer: 2
2022-11-22 19:16:56,071 INFO    SenderThread:37625 [sender.py:transition_state():463] send defer: 3
2022-11-22 19:16:56,072 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,072 INFO    HandlerThread:37625 [handler.py:handle_request_defer():162] handle defer: 3
2022-11-22 19:16:56,072 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,072 INFO    SenderThread:37625 [sender.py:send_request_defer():459] handle sender defer: 3
2022-11-22 19:16:56,072 INFO    SenderThread:37625 [sender.py:transition_state():463] send defer: 4
2022-11-22 19:16:56,072 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,073 INFO    HandlerThread:37625 [handler.py:handle_request_defer():162] handle defer: 4
2022-11-22 19:16:56,073 DEBUG   SenderThread:37625 [sender.py:send():303] send: summary
2022-11-22 19:16:56,073 INFO    SenderThread:37625 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:16:56,073 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,073 INFO    SenderThread:37625 [sender.py:send_request_defer():459] handle sender defer: 4
2022-11-22 19:16:56,073 INFO    SenderThread:37625 [sender.py:transition_state():463] send defer: 5
2022-11-22 19:16:56,074 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,074 INFO    HandlerThread:37625 [handler.py:handle_request_defer():162] handle defer: 5
2022-11-22 19:16:56,074 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,074 INFO    SenderThread:37625 [sender.py:send_request_defer():459] handle sender defer: 5
2022-11-22 19:16:56,139 INFO    Thread-17 :37625 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/wandb-summary.json
2022-11-22 19:16:56,139 INFO    Thread-17 :37625 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/output.log
2022-11-22 19:16:57,847 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:58,141 INFO    Thread-17 :37625 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/output.log
2022-11-22 19:17:01,628 INFO    SenderThread:37625 [sender.py:transition_state():463] send defer: 6
2022-11-22 19:17:01,629 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:17:01,629 INFO    HandlerThread:37625 [handler.py:handle_request_defer():162] handle defer: 6
2022-11-22 19:17:01,629 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: defer
2022-11-22 19:17:01,629 INFO    SenderThread:37625 [sender.py:send_request_defer():459] handle sender defer: 6
2022-11-22 19:17:02,103 INFO    SenderThread:37625 [sender.py:transition_state():463] send defer: 7
2022-11-22 19:17:02,104 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:17:02,105 INFO    HandlerThread:37625 [handler.py:handle_request_defer():162] handle defer: 7
2022-11-22 19:17:02,105 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: defer
2022-11-22 19:17:02,106 INFO    SenderThread:37625 [sender.py:send_request_defer():459] handle sender defer: 7
2022-11-22 19:17:02,106 INFO    SenderThread:37625 [dir_watcher.py:finish():362] shutting down directory watcher
2022-11-22 19:17:02,145 INFO    SenderThread:37625 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/config.yaml
2022-11-22 19:17:02,146 INFO    SenderThread:37625 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/output.log
2022-11-22 19:17:02,148 INFO    SenderThread:37625 [dir_watcher.py:finish():392] scan: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files
2022-11-22 19:17:02,149 INFO    SenderThread:37625 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/wandb-summary.json wandb-summary.json
2022-11-22 19:17:02,150 INFO    SenderThread:37625 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/config.yaml config.yaml
2022-11-22 19:17:02,151 INFO    SenderThread:37625 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/output.log output.log
2022-11-22 19:17:02,151 INFO    SenderThread:37625 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/requirements.txt requirements.txt
2022-11-22 19:17:02,152 INFO    SenderThread:37625 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/conda-environment.yaml conda-environment.yaml
2022-11-22 19:17:02,165 INFO    SenderThread:37625 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/wandb-metadata.json wandb-metadata.json
2022-11-22 19:17:02,166 INFO    SenderThread:37625 [sender.py:transition_state():463] send defer: 8
2022-11-22 19:17:02,218 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:17:02,218 INFO    HandlerThread:37625 [handler.py:handle_request_defer():162] handle defer: 8
2022-11-22 19:17:02,218 DEBUG   SenderThread:37625 [sender.py:send_request():317] send_request: defer
2022-11-22 19:17:02,219 INFO    SenderThread:37625 [sender.py:send_request_defer():459] handle sender defer: 8
2022-11-22 19:17:02,219 INFO    SenderThread:37625 [file_pusher.py:finish():168] shutting down file pusher
2022-11-22 19:17:02,850 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:07,860 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:12,864 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:15,879 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=K6DPlXEfCawdcaKsqBj2H40bxrQguDugOylkaHlHtTznJ%2Bp%2FQL4%2FbPd9vZkNxHPdnAKj8TEQEzOhSGSj8Ww81%2BgZiobld2E9unmZFNX3gaITDHT9q2mRRIoasGOXfnnXMVjvegO0d%2BCEK8MxRgTRNRh1Y3AYHx2kyPM7TwFKU3aLWJmbbwuPB%2FtI1%2F6zcLJyTs4va%2FUdVGA6hd%2FV6XuI4spIA4pNqAxJ87UJeaMlq51qbOeNnVeHS5qnYfJ2K0WCztFHTq99F4X4GgT9Eu%2Fhs5SE%2FfVIU%2BL%2BDgZ%2BXf79Mv7CHuwivEITv%2FWmiclhCy22Wno1SMxTqelIpQLUWVigyQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=K6DPlXEfCawdcaKsqBj2H40bxrQguDugOylkaHlHtTznJ%2Bp%2FQL4%2FbPd9vZkNxHPdnAKj8TEQEzOhSGSj8Ww81%2BgZiobld2E9unmZFNX3gaITDHT9q2mRRIoasGOXfnnXMVjvegO0d%2BCEK8MxRgTRNRh1Y3AYHx2kyPM7TwFKU3aLWJmbbwuPB%2FtI1%2F6zcLJyTs4va%2FUdVGA6hd%2FV6XuI4spIA4pNqAxJ87UJeaMlq51qbOeNnVeHS5qnYfJ2K0WCztFHTq99F4X4GgT9Eu%2Fhs5SE%2FfVIU%2BL%2BDgZ%2BXf79Mv7CHuwivEITv%2FWmiclhCy22Wno1SMxTqelIpQLUWVigyQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae068dd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:15,880 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2650'}
2022-11-22 19:17:15,881 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:17,867 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:22,871 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:26,938 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=K6DPlXEfCawdcaKsqBj2H40bxrQguDugOylkaHlHtTznJ%2Bp%2FQL4%2FbPd9vZkNxHPdnAKj8TEQEzOhSGSj8Ww81%2BgZiobld2E9unmZFNX3gaITDHT9q2mRRIoasGOXfnnXMVjvegO0d%2BCEK8MxRgTRNRh1Y3AYHx2kyPM7TwFKU3aLWJmbbwuPB%2FtI1%2F6zcLJyTs4va%2FUdVGA6hd%2FV6XuI4spIA4pNqAxJ87UJeaMlq51qbOeNnVeHS5qnYfJ2K0WCztFHTq99F4X4GgT9Eu%2Fhs5SE%2FfVIU%2BL%2BDgZ%2BXf79Mv7CHuwivEITv%2FWmiclhCy22Wno1SMxTqelIpQLUWVigyQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=K6DPlXEfCawdcaKsqBj2H40bxrQguDugOylkaHlHtTznJ%2Bp%2FQL4%2FbPd9vZkNxHPdnAKj8TEQEzOhSGSj8Ww81%2BgZiobld2E9unmZFNX3gaITDHT9q2mRRIoasGOXfnnXMVjvegO0d%2BCEK8MxRgTRNRh1Y3AYHx2kyPM7TwFKU3aLWJmbbwuPB%2FtI1%2F6zcLJyTs4va%2FUdVGA6hd%2FV6XuI4spIA4pNqAxJ87UJeaMlq51qbOeNnVeHS5qnYfJ2K0WCztFHTq99F4X4GgT9Eu%2Fhs5SE%2FfVIU%2BL%2BDgZ%2BXf79Mv7CHuwivEITv%2FWmiclhCy22Wno1SMxTqelIpQLUWVigyQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae0685640>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:26,938 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2650'}
2022-11-22 19:17:26,938 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:27,563 ERROR   Thread-23 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gU1bqZZGUKRRjezGFGWAqKP6PBOzf%2BUXKzE%2FvNBg6GtKk3y2cYJYhnqdt32oAZU3v6ysVmSlR3yaoio8zRnjJ%2FtowkL2u0my8IkSdvZDZJ1uMo2NbGanSwoPN%2BVjUUKJKZILjuxIXkN0OTcPbSoNmRpEfxU4XDjYV7sF6ovWMbneBEoo3YgtxeSUbOrhnyCilyYnc3mw0YE8sH9FnmVFjT6TeojaKgit15Z4FdnBTzDXW%2FBH7hyZl7AX5VgDxYkfilK3am5PXcBYo0NHaJTvzH%2B3sWu5rBCgPIyx3TPeAjzAJYmWmWNAEmMd8r%2FrWv0DmlkaRUMyz%2F%2B3ukNnwc2gdw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gU1bqZZGUKRRjezGFGWAqKP6PBOzf%2BUXKzE%2FvNBg6GtKk3y2cYJYhnqdt32oAZU3v6ysVmSlR3yaoio8zRnjJ%2FtowkL2u0my8IkSdvZDZJ1uMo2NbGanSwoPN%2BVjUUKJKZILjuxIXkN0OTcPbSoNmRpEfxU4XDjYV7sF6ovWMbneBEoo3YgtxeSUbOrhnyCilyYnc3mw0YE8sH9FnmVFjT6TeojaKgit15Z4FdnBTzDXW%2FBH7hyZl7AX5VgDxYkfilK3am5PXcBYo0NHaJTvzH%2B3sWu5rBCgPIyx3TPeAjzAJYmWmWNAEmMd8r%2FrWv0DmlkaRUMyz%2F%2B3ukNnwc2gdw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1b04056fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:27,564 ERROR   Thread-23 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11206'}
2022-11-22 19:17:27,564 ERROR   Thread-23 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:27,571 ERROR   Thread-21 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ZCzWu636QIYwO%2FeohjYPXVB%2Bb7VafsjBaZd%2BbQ0RngoKhX6RzDbDr%2FnLyk5E%2FFM4sl9fhTfQErpqSOjygD%2BvjqSHcIDOl%2BJUP9oWSPl%2BnRpOrlBXmfhmI2klCQASN9egcVqpuYLAvw6UfEw3ObSWqeZ7NgFK%2Fd9a4IOjpwFzHIhW2Ix109oS0OZfW34a8DkEQ1GABzJQEXvUGE32IAurgobrqLti5LD%2Fm%2FZdq7%2BWXJXFF8G3yaggtNLhe0VT%2F1UqyPkfCsdSBLW%2F%2Bocd4PpWhUvdwXaMHVnaoFd%2Fs%2B5OqDVCrJuV2JXCCse9Dlx%2B%2B29WIEONv9shPFEo6aN4QYLJaQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ZCzWu636QIYwO%2FeohjYPXVB%2Bb7VafsjBaZd%2BbQ0RngoKhX6RzDbDr%2FnLyk5E%2FFM4sl9fhTfQErpqSOjygD%2BvjqSHcIDOl%2BJUP9oWSPl%2BnRpOrlBXmfhmI2klCQASN9egcVqpuYLAvw6UfEw3ObSWqeZ7NgFK%2Fd9a4IOjpwFzHIhW2Ix109oS0OZfW34a8DkEQ1GABzJQEXvUGE32IAurgobrqLti5LD%2Fm%2FZdq7%2BWXJXFF8G3yaggtNLhe0VT%2F1UqyPkfCsdSBLW%2F%2Bocd4PpWhUvdwXaMHVnaoFd%2Fs%2B5OqDVCrJuV2JXCCse9Dlx%2B%2B29WIEONv9shPFEo6aN4QYLJaQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1b040219a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:27,571 ERROR   Thread-21 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:17:27,571 ERROR   Thread-21 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:27,574 ERROR   Thread-24 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gbSegupjE64IoCif8kBuvbtj4LhCvZKeBlNKt6EMVB25gJoSSvbW4ihuETv8KLzeWneTKGkBhQOpatIQV678L%2FgUXEhcijvCphDXR8%2FA3MVF1Wi5uf%2FAdW9DHyobs1v3CY827dG1SMVEQ6tuZ0wdH2rZ3Z%2BfUglrBjliOHqBJzB1nXbMLa%2FcEo3QjBhsDbIP255doeCD7vqfxahDSfu5UyMImoXc8uaUP3xucwlPf1ExeUYEbzWdlnlkkOSzFAys1T86U3lBRDBxWzWiYv0sdKBZ2AnwvwrZiJrumxDKh042MMRu1bq%2FTO3%2FqB2yStmqKEKK5mUsSsS%2BaQK0jPEASQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gbSegupjE64IoCif8kBuvbtj4LhCvZKeBlNKt6EMVB25gJoSSvbW4ihuETv8KLzeWneTKGkBhQOpatIQV678L%2FgUXEhcijvCphDXR8%2FA3MVF1Wi5uf%2FAdW9DHyobs1v3CY827dG1SMVEQ6tuZ0wdH2rZ3Z%2BfUglrBjliOHqBJzB1nXbMLa%2FcEo3QjBhsDbIP255doeCD7vqfxahDSfu5UyMImoXc8uaUP3xucwlPf1ExeUYEbzWdlnlkkOSzFAys1T86U3lBRDBxWzWiYv0sdKBZ2AnwvwrZiJrumxDKh042MMRu1bq%2FTO3%2FqB2yStmqKEKK5mUsSsS%2BaQK0jPEASQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae06a2c70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:27,574 ERROR   Thread-24 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:17:27,574 ERROR   Thread-24 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:27,674 ERROR   Thread-25 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KrQRql8XMsGIk8ec2EwO%2FmCZmNCIG0rporkt5aFcsUjszNeh%2FBWrK7M8%2FNGEMhX8pQmG9vUfVfkHYiN%2BPlpJmkx0GYB2v%2BFdXHPyhmTBJPtRlNb2A4mQUbD04%2BIdW1VYz5GfcW8YF%2FdZyXpa3xk7Go2nwR2dTDftg160d5NJLBZjvDYPB0FMCA%2BTuyVCnda2lL9N6AUY%2FdGa0yfFdn5so%2Fa7qRvSIaSlai0s1i93wvkbMQu2SAg%2F2vIJhIPkEgC0Zo0fsUFlMADDwXpXDx3RYn6ZzG6MQkdzSwrOKBuMbcQJJyHjy0dUBiAnUnYWFOgEeo3PWsbGe2UgaNp90Xi9RQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KrQRql8XMsGIk8ec2EwO%2FmCZmNCIG0rporkt5aFcsUjszNeh%2FBWrK7M8%2FNGEMhX8pQmG9vUfVfkHYiN%2BPlpJmkx0GYB2v%2BFdXHPyhmTBJPtRlNb2A4mQUbD04%2BIdW1VYz5GfcW8YF%2FdZyXpa3xk7Go2nwR2dTDftg160d5NJLBZjvDYPB0FMCA%2BTuyVCnda2lL9N6AUY%2FdGa0yfFdn5so%2Fa7qRvSIaSlai0s1i93wvkbMQu2SAg%2F2vIJhIPkEgC0Zo0fsUFlMADDwXpXDx3RYn6ZzG6MQkdzSwrOKBuMbcQJJyHjy0dUBiAnUnYWFOgEeo3PWsbGe2UgaNp90Xi9RQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae0693340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:27,675 ERROR   Thread-25 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:17:27,675 ERROR   Thread-25 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:27,738 ERROR   Thread-22 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=C6dxuT0RHLZg4eMdg5itdzf7AcZVPTjAMo4P4LT3HLxVrjdvLnEORUaUVhZL6pNwxhtS11Xnzj8KD0ctzN1as2fqJwh8bo1EbPuatlq%2F3jlUcGLZyyU7wp1Y3utCuqc9phW7dciXV%2FWMvFlL%2B6RqTdLUEvyeVzxT9LjP3DWW9dTsaVeXc5Y%2B1pNhg6b4aOG5Pn1sf6Em4LApnfDwroiB%2FKfzvpal8Fiye8rhjVt6Y%2BOhVmgSVFaDE6v%2F4maE4IqNgVl%2BnMaV%2FMIYV%2B4hz%2FwWhcIXdrSpTydz0%2BcbjbBw7%2FjgqiOcmG2qcZy%2FyMY9dwkYppX%2F5rhcvKST54ErP3SwgA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=C6dxuT0RHLZg4eMdg5itdzf7AcZVPTjAMo4P4LT3HLxVrjdvLnEORUaUVhZL6pNwxhtS11Xnzj8KD0ctzN1as2fqJwh8bo1EbPuatlq%2F3jlUcGLZyyU7wp1Y3utCuqc9phW7dciXV%2FWMvFlL%2B6RqTdLUEvyeVzxT9LjP3DWW9dTsaVeXc5Y%2B1pNhg6b4aOG5Pn1sf6Em4LApnfDwroiB%2FKfzvpal8Fiye8rhjVt6Y%2BOhVmgSVFaDE6v%2F4maE4IqNgVl%2BnMaV%2FMIYV%2B4hz%2FwWhcIXdrSpTydz0%2BcbjbBw7%2FjgqiOcmG2qcZy%2FyMY9dwkYppX%2F5rhcvKST54ErP3SwgA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1b0403afa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:27,738 ERROR   Thread-22 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:17:27,738 ERROR   Thread-22 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:27,874 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:32,902 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:37,904 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:38,647 ERROR   Thread-23 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gU1bqZZGUKRRjezGFGWAqKP6PBOzf%2BUXKzE%2FvNBg6GtKk3y2cYJYhnqdt32oAZU3v6ysVmSlR3yaoio8zRnjJ%2FtowkL2u0my8IkSdvZDZJ1uMo2NbGanSwoPN%2BVjUUKJKZILjuxIXkN0OTcPbSoNmRpEfxU4XDjYV7sF6ovWMbneBEoo3YgtxeSUbOrhnyCilyYnc3mw0YE8sH9FnmVFjT6TeojaKgit15Z4FdnBTzDXW%2FBH7hyZl7AX5VgDxYkfilK3am5PXcBYo0NHaJTvzH%2B3sWu5rBCgPIyx3TPeAjzAJYmWmWNAEmMd8r%2FrWv0DmlkaRUMyz%2F%2B3ukNnwc2gdw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gU1bqZZGUKRRjezGFGWAqKP6PBOzf%2BUXKzE%2FvNBg6GtKk3y2cYJYhnqdt32oAZU3v6ysVmSlR3yaoio8zRnjJ%2FtowkL2u0my8IkSdvZDZJ1uMo2NbGanSwoPN%2BVjUUKJKZILjuxIXkN0OTcPbSoNmRpEfxU4XDjYV7sF6ovWMbneBEoo3YgtxeSUbOrhnyCilyYnc3mw0YE8sH9FnmVFjT6TeojaKgit15Z4FdnBTzDXW%2FBH7hyZl7AX5VgDxYkfilK3am5PXcBYo0NHaJTvzH%2B3sWu5rBCgPIyx3TPeAjzAJYmWmWNAEmMd8r%2FrWv0DmlkaRUMyz%2F%2B3ukNnwc2gdw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae069ccd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:38,648 ERROR   Thread-23 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11206'}
2022-11-22 19:17:38,649 ERROR   Thread-23 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:38,759 ERROR   Thread-21 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ZCzWu636QIYwO%2FeohjYPXVB%2Bb7VafsjBaZd%2BbQ0RngoKhX6RzDbDr%2FnLyk5E%2FFM4sl9fhTfQErpqSOjygD%2BvjqSHcIDOl%2BJUP9oWSPl%2BnRpOrlBXmfhmI2klCQASN9egcVqpuYLAvw6UfEw3ObSWqeZ7NgFK%2Fd9a4IOjpwFzHIhW2Ix109oS0OZfW34a8DkEQ1GABzJQEXvUGE32IAurgobrqLti5LD%2Fm%2FZdq7%2BWXJXFF8G3yaggtNLhe0VT%2F1UqyPkfCsdSBLW%2F%2Bocd4PpWhUvdwXaMHVnaoFd%2Fs%2B5OqDVCrJuV2JXCCse9Dlx%2B%2B29WIEONv9shPFEo6aN4QYLJaQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ZCzWu636QIYwO%2FeohjYPXVB%2Bb7VafsjBaZd%2BbQ0RngoKhX6RzDbDr%2FnLyk5E%2FFM4sl9fhTfQErpqSOjygD%2BvjqSHcIDOl%2BJUP9oWSPl%2BnRpOrlBXmfhmI2klCQASN9egcVqpuYLAvw6UfEw3ObSWqeZ7NgFK%2Fd9a4IOjpwFzHIhW2Ix109oS0OZfW34a8DkEQ1GABzJQEXvUGE32IAurgobrqLti5LD%2Fm%2FZdq7%2BWXJXFF8G3yaggtNLhe0VT%2F1UqyPkfCsdSBLW%2F%2Bocd4PpWhUvdwXaMHVnaoFd%2Fs%2B5OqDVCrJuV2JXCCse9Dlx%2B%2B29WIEONv9shPFEo6aN4QYLJaQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae069c490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:38,759 ERROR   Thread-21 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:17:38,759 ERROR   Thread-21 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:38,867 ERROR   Thread-24 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gbSegupjE64IoCif8kBuvbtj4LhCvZKeBlNKt6EMVB25gJoSSvbW4ihuETv8KLzeWneTKGkBhQOpatIQV678L%2FgUXEhcijvCphDXR8%2FA3MVF1Wi5uf%2FAdW9DHyobs1v3CY827dG1SMVEQ6tuZ0wdH2rZ3Z%2BfUglrBjliOHqBJzB1nXbMLa%2FcEo3QjBhsDbIP255doeCD7vqfxahDSfu5UyMImoXc8uaUP3xucwlPf1ExeUYEbzWdlnlkkOSzFAys1T86U3lBRDBxWzWiYv0sdKBZ2AnwvwrZiJrumxDKh042MMRu1bq%2FTO3%2FqB2yStmqKEKK5mUsSsS%2BaQK0jPEASQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gbSegupjE64IoCif8kBuvbtj4LhCvZKeBlNKt6EMVB25gJoSSvbW4ihuETv8KLzeWneTKGkBhQOpatIQV678L%2FgUXEhcijvCphDXR8%2FA3MVF1Wi5uf%2FAdW9DHyobs1v3CY827dG1SMVEQ6tuZ0wdH2rZ3Z%2BfUglrBjliOHqBJzB1nXbMLa%2FcEo3QjBhsDbIP255doeCD7vqfxahDSfu5UyMImoXc8uaUP3xucwlPf1ExeUYEbzWdlnlkkOSzFAys1T86U3lBRDBxWzWiYv0sdKBZ2AnwvwrZiJrumxDKh042MMRu1bq%2FTO3%2FqB2yStmqKEKK5mUsSsS%2BaQK0jPEASQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae0693550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:38,867 ERROR   Thread-24 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:17:38,867 ERROR   Thread-24 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:38,907 ERROR   Thread-22 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=C6dxuT0RHLZg4eMdg5itdzf7AcZVPTjAMo4P4LT3HLxVrjdvLnEORUaUVhZL6pNwxhtS11Xnzj8KD0ctzN1as2fqJwh8bo1EbPuatlq%2F3jlUcGLZyyU7wp1Y3utCuqc9phW7dciXV%2FWMvFlL%2B6RqTdLUEvyeVzxT9LjP3DWW9dTsaVeXc5Y%2B1pNhg6b4aOG5Pn1sf6Em4LApnfDwroiB%2FKfzvpal8Fiye8rhjVt6Y%2BOhVmgSVFaDE6v%2F4maE4IqNgVl%2BnMaV%2FMIYV%2B4hz%2FwWhcIXdrSpTydz0%2BcbjbBw7%2FjgqiOcmG2qcZy%2FyMY9dwkYppX%2F5rhcvKST54ErP3SwgA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=C6dxuT0RHLZg4eMdg5itdzf7AcZVPTjAMo4P4LT3HLxVrjdvLnEORUaUVhZL6pNwxhtS11Xnzj8KD0ctzN1as2fqJwh8bo1EbPuatlq%2F3jlUcGLZyyU7wp1Y3utCuqc9phW7dciXV%2FWMvFlL%2B6RqTdLUEvyeVzxT9LjP3DWW9dTsaVeXc5Y%2B1pNhg6b4aOG5Pn1sf6Em4LApnfDwroiB%2FKfzvpal8Fiye8rhjVt6Y%2BOhVmgSVFaDE6v%2F4maE4IqNgVl%2BnMaV%2FMIYV%2B4hz%2FwWhcIXdrSpTydz0%2BcbjbBw7%2FjgqiOcmG2qcZy%2FyMY9dwkYppX%2F5rhcvKST54ErP3SwgA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae06a2a00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:38,907 ERROR   Thread-22 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:17:38,907 ERROR   Thread-22 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:38,914 ERROR   Thread-25 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KrQRql8XMsGIk8ec2EwO%2FmCZmNCIG0rporkt5aFcsUjszNeh%2FBWrK7M8%2FNGEMhX8pQmG9vUfVfkHYiN%2BPlpJmkx0GYB2v%2BFdXHPyhmTBJPtRlNb2A4mQUbD04%2BIdW1VYz5GfcW8YF%2FdZyXpa3xk7Go2nwR2dTDftg160d5NJLBZjvDYPB0FMCA%2BTuyVCnda2lL9N6AUY%2FdGa0yfFdn5so%2Fa7qRvSIaSlai0s1i93wvkbMQu2SAg%2F2vIJhIPkEgC0Zo0fsUFlMADDwXpXDx3RYn6ZzG6MQkdzSwrOKBuMbcQJJyHjy0dUBiAnUnYWFOgEeo3PWsbGe2UgaNp90Xi9RQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KrQRql8XMsGIk8ec2EwO%2FmCZmNCIG0rporkt5aFcsUjszNeh%2FBWrK7M8%2FNGEMhX8pQmG9vUfVfkHYiN%2BPlpJmkx0GYB2v%2BFdXHPyhmTBJPtRlNb2A4mQUbD04%2BIdW1VYz5GfcW8YF%2FdZyXpa3xk7Go2nwR2dTDftg160d5NJLBZjvDYPB0FMCA%2BTuyVCnda2lL9N6AUY%2FdGa0yfFdn5so%2Fa7qRvSIaSlai0s1i93wvkbMQu2SAg%2F2vIJhIPkEgC0Zo0fsUFlMADDwXpXDx3RYn6ZzG6MQkdzSwrOKBuMbcQJJyHjy0dUBiAnUnYWFOgEeo3PWsbGe2UgaNp90Xi9RQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae06a2790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:38,915 ERROR   Thread-25 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:17:38,915 ERROR   Thread-25 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:38,999 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=K6DPlXEfCawdcaKsqBj2H40bxrQguDugOylkaHlHtTznJ%2Bp%2FQL4%2FbPd9vZkNxHPdnAKj8TEQEzOhSGSj8Ww81%2BgZiobld2E9unmZFNX3gaITDHT9q2mRRIoasGOXfnnXMVjvegO0d%2BCEK8MxRgTRNRh1Y3AYHx2kyPM7TwFKU3aLWJmbbwuPB%2FtI1%2F6zcLJyTs4va%2FUdVGA6hd%2FV6XuI4spIA4pNqAxJ87UJeaMlq51qbOeNnVeHS5qnYfJ2K0WCztFHTq99F4X4GgT9Eu%2Fhs5SE%2FfVIU%2BL%2BDgZ%2BXf79Mv7CHuwivEITv%2FWmiclhCy22Wno1SMxTqelIpQLUWVigyQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=K6DPlXEfCawdcaKsqBj2H40bxrQguDugOylkaHlHtTznJ%2Bp%2FQL4%2FbPd9vZkNxHPdnAKj8TEQEzOhSGSj8Ww81%2BgZiobld2E9unmZFNX3gaITDHT9q2mRRIoasGOXfnnXMVjvegO0d%2BCEK8MxRgTRNRh1Y3AYHx2kyPM7TwFKU3aLWJmbbwuPB%2FtI1%2F6zcLJyTs4va%2FUdVGA6hd%2FV6XuI4spIA4pNqAxJ87UJeaMlq51qbOeNnVeHS5qnYfJ2K0WCztFHTq99F4X4GgT9Eu%2Fhs5SE%2FfVIU%2BL%2BDgZ%2BXf79Mv7CHuwivEITv%2FWmiclhCy22Wno1SMxTqelIpQLUWVigyQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1b04056d30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:38,999 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2650'}
2022-11-22 19:17:38,999 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:42,913 DEBUG   HandlerThread:37625 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:48,794 WARNING StreamThr :37625 [internal.py:is_dead():385] Internal process exiting, parent pid 37526 disappeared
2022-11-22 19:17:48,794 ERROR   StreamThr :37625 [internal.py:wandb_internal():147] Internal process shutdown.
2022-11-22 19:17:48,921 INFO    HandlerThread:37625 [handler.py:finish():814] shutting down handler
2022-11-22 19:17:49,107 INFO    WriterThread:37625 [datastore.py:close():279] close: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/run-3epim9cz.wandb
2022-11-22 19:17:49,235 INFO    SenderThread:37625 [sender.py:finish():1331] shutting down sender
2022-11-22 19:17:49,236 INFO    SenderThread:37625 [file_pusher.py:finish():168] shutting down file pusher
2022-11-22 19:17:49,236 INFO    SenderThread:37625 [file_pusher.py:join():173] waiting for file pusher
2022-11-22 19:17:50,886 ERROR   Thread-23 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gU1bqZZGUKRRjezGFGWAqKP6PBOzf%2BUXKzE%2FvNBg6GtKk3y2cYJYhnqdt32oAZU3v6ysVmSlR3yaoio8zRnjJ%2FtowkL2u0my8IkSdvZDZJ1uMo2NbGanSwoPN%2BVjUUKJKZILjuxIXkN0OTcPbSoNmRpEfxU4XDjYV7sF6ovWMbneBEoo3YgtxeSUbOrhnyCilyYnc3mw0YE8sH9FnmVFjT6TeojaKgit15Z4FdnBTzDXW%2FBH7hyZl7AX5VgDxYkfilK3am5PXcBYo0NHaJTvzH%2B3sWu5rBCgPIyx3TPeAjzAJYmWmWNAEmMd8r%2FrWv0DmlkaRUMyz%2F%2B3ukNnwc2gdw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/output.log?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gU1bqZZGUKRRjezGFGWAqKP6PBOzf%2BUXKzE%2FvNBg6GtKk3y2cYJYhnqdt32oAZU3v6ysVmSlR3yaoio8zRnjJ%2FtowkL2u0my8IkSdvZDZJ1uMo2NbGanSwoPN%2BVjUUKJKZILjuxIXkN0OTcPbSoNmRpEfxU4XDjYV7sF6ovWMbneBEoo3YgtxeSUbOrhnyCilyYnc3mw0YE8sH9FnmVFjT6TeojaKgit15Z4FdnBTzDXW%2FBH7hyZl7AX5VgDxYkfilK3am5PXcBYo0NHaJTvzH%2B3sWu5rBCgPIyx3TPeAjzAJYmWmWNAEmMd8r%2FrWv0DmlkaRUMyz%2F%2B3ukNnwc2gdw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1b0403a490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:50,886 ERROR   Thread-23 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11206'}
2022-11-22 19:17:50,886 ERROR   Thread-23 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:50,919 ERROR   Thread-21 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ZCzWu636QIYwO%2FeohjYPXVB%2Bb7VafsjBaZd%2BbQ0RngoKhX6RzDbDr%2FnLyk5E%2FFM4sl9fhTfQErpqSOjygD%2BvjqSHcIDOl%2BJUP9oWSPl%2BnRpOrlBXmfhmI2klCQASN9egcVqpuYLAvw6UfEw3ObSWqeZ7NgFK%2Fd9a4IOjpwFzHIhW2Ix109oS0OZfW34a8DkEQ1GABzJQEXvUGE32IAurgobrqLti5LD%2Fm%2FZdq7%2BWXJXFF8G3yaggtNLhe0VT%2F1UqyPkfCsdSBLW%2F%2Bocd4PpWhUvdwXaMHVnaoFd%2Fs%2B5OqDVCrJuV2JXCCse9Dlx%2B%2B29WIEONv9shPFEo6aN4QYLJaQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-summary.json?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ZCzWu636QIYwO%2FeohjYPXVB%2Bb7VafsjBaZd%2BbQ0RngoKhX6RzDbDr%2FnLyk5E%2FFM4sl9fhTfQErpqSOjygD%2BvjqSHcIDOl%2BJUP9oWSPl%2BnRpOrlBXmfhmI2klCQASN9egcVqpuYLAvw6UfEw3ObSWqeZ7NgFK%2Fd9a4IOjpwFzHIhW2Ix109oS0OZfW34a8DkEQ1GABzJQEXvUGE32IAurgobrqLti5LD%2Fm%2FZdq7%2BWXJXFF8G3yaggtNLhe0VT%2F1UqyPkfCsdSBLW%2F%2Bocd4PpWhUvdwXaMHVnaoFd%2Fs%2B5OqDVCrJuV2JXCCse9Dlx%2B%2B29WIEONv9shPFEo6aN4QYLJaQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae068de50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:50,919 ERROR   Thread-21 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:17:50,919 ERROR   Thread-21 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:51,003 ERROR   Thread-25 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KrQRql8XMsGIk8ec2EwO%2FmCZmNCIG0rporkt5aFcsUjszNeh%2FBWrK7M8%2FNGEMhX8pQmG9vUfVfkHYiN%2BPlpJmkx0GYB2v%2BFdXHPyhmTBJPtRlNb2A4mQUbD04%2BIdW1VYz5GfcW8YF%2FdZyXpa3xk7Go2nwR2dTDftg160d5NJLBZjvDYPB0FMCA%2BTuyVCnda2lL9N6AUY%2FdGa0yfFdn5so%2Fa7qRvSIaSlai0s1i93wvkbMQu2SAg%2F2vIJhIPkEgC0Zo0fsUFlMADDwXpXDx3RYn6ZzG6MQkdzSwrOKBuMbcQJJyHjy0dUBiAnUnYWFOgEeo3PWsbGe2UgaNp90Xi9RQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/conda-environment.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=KrQRql8XMsGIk8ec2EwO%2FmCZmNCIG0rporkt5aFcsUjszNeh%2FBWrK7M8%2FNGEMhX8pQmG9vUfVfkHYiN%2BPlpJmkx0GYB2v%2BFdXHPyhmTBJPtRlNb2A4mQUbD04%2BIdW1VYz5GfcW8YF%2FdZyXpa3xk7Go2nwR2dTDftg160d5NJLBZjvDYPB0FMCA%2BTuyVCnda2lL9N6AUY%2FdGa0yfFdn5so%2Fa7qRvSIaSlai0s1i93wvkbMQu2SAg%2F2vIJhIPkEgC0Zo0fsUFlMADDwXpXDx3RYn6ZzG6MQkdzSwrOKBuMbcQJJyHjy0dUBiAnUnYWFOgEeo3PWsbGe2UgaNp90Xi9RQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae068d850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,003 ERROR   Thread-25 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:17:51,004 ERROR   Thread-25 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:51,026 ERROR   Thread-24 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gbSegupjE64IoCif8kBuvbtj4LhCvZKeBlNKt6EMVB25gJoSSvbW4ihuETv8KLzeWneTKGkBhQOpatIQV678L%2FgUXEhcijvCphDXR8%2FA3MVF1Wi5uf%2FAdW9DHyobs1v3CY827dG1SMVEQ6tuZ0wdH2rZ3Z%2BfUglrBjliOHqBJzB1nXbMLa%2FcEo3QjBhsDbIP255doeCD7vqfxahDSfu5UyMImoXc8uaUP3xucwlPf1ExeUYEbzWdlnlkkOSzFAys1T86U3lBRDBxWzWiYv0sdKBZ2AnwvwrZiJrumxDKh042MMRu1bq%2FTO3%2FqB2yStmqKEKK5mUsSsS%2BaQK0jPEASQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/requirements.txt?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=gbSegupjE64IoCif8kBuvbtj4LhCvZKeBlNKt6EMVB25gJoSSvbW4ihuETv8KLzeWneTKGkBhQOpatIQV678L%2FgUXEhcijvCphDXR8%2FA3MVF1Wi5uf%2FAdW9DHyobs1v3CY827dG1SMVEQ6tuZ0wdH2rZ3Z%2BfUglrBjliOHqBJzB1nXbMLa%2FcEo3QjBhsDbIP255doeCD7vqfxahDSfu5UyMImoXc8uaUP3xucwlPf1ExeUYEbzWdlnlkkOSzFAys1T86U3lBRDBxWzWiYv0sdKBZ2AnwvwrZiJrumxDKh042MMRu1bq%2FTO3%2FqB2yStmqKEKK5mUsSsS%2BaQK0jPEASQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae069c550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,026 ERROR   Thread-24 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:17:51,026 ERROR   Thread-24 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:51,142 ERROR   Thread-22 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=C6dxuT0RHLZg4eMdg5itdzf7AcZVPTjAMo4P4LT3HLxVrjdvLnEORUaUVhZL6pNwxhtS11Xnzj8KD0ctzN1as2fqJwh8bo1EbPuatlq%2F3jlUcGLZyyU7wp1Y3utCuqc9phW7dciXV%2FWMvFlL%2B6RqTdLUEvyeVzxT9LjP3DWW9dTsaVeXc5Y%2B1pNhg6b4aOG5Pn1sf6Em4LApnfDwroiB%2FKfzvpal8Fiye8rhjVt6Y%2BOhVmgSVFaDE6v%2F4maE4IqNgVl%2BnMaV%2FMIYV%2B4hz%2FwWhcIXdrSpTydz0%2BcbjbBw7%2FjgqiOcmG2qcZy%2FyMY9dwkYppX%2F5rhcvKST54ErP3SwgA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/config.yaml?Expires=1669202237&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=C6dxuT0RHLZg4eMdg5itdzf7AcZVPTjAMo4P4LT3HLxVrjdvLnEORUaUVhZL6pNwxhtS11Xnzj8KD0ctzN1as2fqJwh8bo1EbPuatlq%2F3jlUcGLZyyU7wp1Y3utCuqc9phW7dciXV%2FWMvFlL%2B6RqTdLUEvyeVzxT9LjP3DWW9dTsaVeXc5Y%2B1pNhg6b4aOG5Pn1sf6Em4LApnfDwroiB%2FKfzvpal8Fiye8rhjVt6Y%2BOhVmgSVFaDE6v%2F4maE4IqNgVl%2BnMaV%2FMIYV%2B4hz%2FwWhcIXdrSpTydz0%2BcbjbBw7%2FjgqiOcmG2qcZy%2FyMY9dwkYppX%2F5rhcvKST54ErP3SwgA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1b04056d00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,142 ERROR   Thread-22 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:17:51,142 ERROR   Thread-22 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:53,243 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=K6DPlXEfCawdcaKsqBj2H40bxrQguDugOylkaHlHtTznJ%2Bp%2FQL4%2FbPd9vZkNxHPdnAKj8TEQEzOhSGSj8Ww81%2BgZiobld2E9unmZFNX3gaITDHT9q2mRRIoasGOXfnnXMVjvegO0d%2BCEK8MxRgTRNRh1Y3AYHx2kyPM7TwFKU3aLWJmbbwuPB%2FtI1%2F6zcLJyTs4va%2FUdVGA6hd%2FV6XuI4spIA4pNqAxJ87UJeaMlq51qbOeNnVeHS5qnYfJ2K0WCztFHTq99F4X4GgT9Eu%2Fhs5SE%2FfVIU%2BL%2BDgZ%2BXf79Mv7CHuwivEITv%2FWmiclhCy22Wno1SMxTqelIpQLUWVigyQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/3epim9cz/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=K6DPlXEfCawdcaKsqBj2H40bxrQguDugOylkaHlHtTznJ%2Bp%2FQL4%2FbPd9vZkNxHPdnAKj8TEQEzOhSGSj8Ww81%2BgZiobld2E9unmZFNX3gaITDHT9q2mRRIoasGOXfnnXMVjvegO0d%2BCEK8MxRgTRNRh1Y3AYHx2kyPM7TwFKU3aLWJmbbwuPB%2FtI1%2F6zcLJyTs4va%2FUdVGA6hd%2FV6XuI4spIA4pNqAxJ87UJeaMlq51qbOeNnVeHS5qnYfJ2K0WCztFHTq99F4X4GgT9Eu%2Fhs5SE%2FfVIU%2BL%2BDgZ%2BXf79Mv7CHuwivEITv%2FWmiclhCy22Wno1SMxTqelIpQLUWVigyQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ae06a2520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:53,244 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2650'}
2022-11-22 19:17:53,244 ERROR   Thread-20 :37625 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:59,287 INFO    Thread-21 :37625 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/wandb-summary.json
2022-11-22 19:17:59,309 INFO    Thread-22 :37625 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/config.yaml
2022-11-22 19:17:59,311 INFO    Thread-25 :37625 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/conda-environment.yaml
2022-11-22 19:17:59,356 INFO    Thread-23 :37625 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/output.log
2022-11-22 19:17:59,378 INFO    Thread-24 :37625 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-3epim9cz/files/requirements.txt
2022-11-22 19:18:03,589 INFO    Thread-20 :37625 [upload_job.py:push():143] Uploaded file /tmp/tmpadpbzho2wandb/4wbbp32n-wandb-metadata.json
2022-11-22 19:18:03,790 INFO    Thread-16 :37625 [sender.py:transition_state():463] send defer: 9
